AWSTemplateFormatVersion: '2010-09-09'
Description: Template create s3 bucket/policy-destinnt

Parameters:
  Versao:
    Type: String
    Default: 1
  Env:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - hml
      - prd
  S3BucketName:
    Description: Bucket Name
    Type: String
    Default: eliezerraj-908671954593-crl-truststore
  S3BucketReplicationName:
    Description: Name Bucket Replication
    Type: String
    Default: eliezerraj-992382474575-crl-truststore
    
Resources:
  S3CRLBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref S3BucketName
      VersioningConfiguration:
        Status: Enabled
      ReplicationConfiguration:
        Role: !GetAtt
          - BucketReplicationRole
          - Arn
        Rules:
          - Destination:
              Bucket: !Join
                - ''
                - - 'arn:aws:s3:::'
                  - !Join
                    - '-'
                    - - !Ref 'AWS::Region'
                      - !Ref 'AWS::StackName'
                      - replicationbucket
              StorageClass: STANDARD
            Id: Backup
            Prefix: ''
            Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: 'AES256'
      Tags:
      - Key: env
        Value: !Ref Env
      - Key: stack
        Value: !Sub ${AWS::StackName}
      - Key: name
        Value: !Join ['', [!Ref S3BucketName, "-Bucket"]]
      - Key: resource
        Value: bucket-s3

  BucketReplicationRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service:
                - s3.amazonaws.com
      Tags:
      - Key: env
        Value: !Ref Env
      - Key: stack
        Value: !Sub ${AWS::StackName}
      - Key: name
        Value: !Join ['', [!Ref S3BucketName, "-Bucket"]]
      - Key: resource
        Value: bucket-s3

  BucketReplicationPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - 's3:GetReplicationConfiguration'
              - 's3:ListBucket'
            Effect: Allow
            Resource:
              - !Join
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref S3CRLBucket
          - Action:
              - 's3:GetObjectVersion'
              - 's3:GetObjectVersionAcl'
            Effect: Allow
            Resource:
              - !Join
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref S3CRLBucket
                  - /*
          - Action:
              - 's3:ReplicateObject'
              - 's3:ReplicateDelete'
            Effect: Allow
            Resource:
              - !Join
                - ''
                - - 'arn:aws:s3:::'
                  - !Join
                    - '-'
                    - - !Ref 'AWS::Region'
                      - !Ref 'AWS::StackName'
                      - replicationbucket
                  - /*
      PolicyName: BucketReplicationPolicy
      Roles:
        - !Ref BucketReplicationRole

Outputs:
  BucketName:
    Value: !Ref S3CRLBucket
    Description: The name of the bucket
  BucketArn: 
    Value: !GetAtt S3CRLBucket.Arn
    Description: The buckey ARN